layout_spectrum: 0.4178499549161643
typography_spectrum: 0.028969600098207593
color:
  brandStrength: 0.2850702414289117
  lightness: 0.7244676537811756
  saturation: 0.034301476553082466
  rhythmicContrast: 0.38490243977867067
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: lionhearted.com
